### PR TITLE
respect baseurl from config in template urls

### PR DESCRIPTION
**Pull request by vpeil**
Running the jskos-server behind a proxy and configuring `baseUrl` accordingly, the links do not repect these settings.

### CODE REVIEW

**Comment by stefandesu** [comment]
Thanks for your contribution! I'm a little bit confused though. If the `baseUrl` is not included in the links in the template, the browser should automatically append it to the current URL. So if the configured `baseUrl` is the only URL where your instance is accessible, the links should be correct. It works for our public instance which is also behind a proxy: https://coli-conc.gbv.de/api/

Or am I missing something?

**Comment by vpeil** [comment]
You are right. This would work with a simple proxy setup.

My setup is a bit more complex:

```
<VirtualHost *:80>
  ServerName example.com
  
  # forward to the jskos-server
  proxyPass /api http://127.0.0.1:3002
 
  # forward to my main application (in this case a perl dancer app)
  ProxyPass / http://127.0.0.1:3001/
  ProxyPassReverse / http://127.0.0.1:3001/
</VirtualHost>
```

Now, all the links look like http://example.com/voc, but should be http://example.com/api/voc (if baseUrl is configured correctly).

**Comment by stefandesu** [comment]
Ah, so it's the missing trailing slash that's causing the problem. Would #86 (i.e. a redirect from `/api` to `/api/`) fix this issue? I feel like appending the `baseUrl` everywhere in the template is not a good solution.

**Comment by vpeil** [comment]
ok, I re-configured my environment. yes, it's working with the trailing slash. I don't know how hard it is to fix #86, but at least some hints in the documentation would be useful. Thanks so far!

**Comment by stefandesu** [comment]
> but at least some hints in the documentation would be useful

Yeah absolutely! Thanks for bringing this up in the first place. Either I'll fix it via #86 or I'll adjust the documentation.

**Comment by stefandesu** [comment]
@vpeil It seems that making jskos-server deal with this issue is either not possible or (if it was possible) probably not the right solution. Could you take a look at [this](https://github.com/gbv/jskos-server/tree/dev#running-behind-a-reverse-proxy) and tell me whether that would have cleared your issue in the first place? Thanks!

**Comment by vpeil** [comment]
> @vpeil It seems that making jskos-server deal with this issue is either not possible or (if it was possible) probably not the right solution. Could you take a look at [this](https://github.com/gbv/jskos-server/tree/dev#running-behind-a-reverse-proxy) and tell me whether that would have cleared your issue in the first place? Thanks!

Thanks! Yes, the setting works fine for me.

**Pull request closed without merging**
